name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch (adjust as needed)
  pull_request:
    branches: [ main ] # Trigger on pull requests to the main branch

jobs:
  hello_job:
    name: Hello Message
    runs-on: ubuntu-latest # Runs on a GitHub-hosted Linux runner
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Run on all three OS
    steps:
      - name: Echo Hello Message
        run: echo "Hi, I am from Mihir Limbad COSC 1209 class (on ${{ matrix.os }})"

  build_java_app:
    name: Build Java App
    needs: hello_job # Make sure hello_job runs first
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact  # Optional: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Java-App-Artifact
          path: build/libs/*  # Adjust path as needed

  build_docker_image:
    name: Build Docker Image
    needs: build_java_app # Depends on successful Java build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only on pushes (not PRs)
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby:buildkit
      - name: Login to Docker Hub (or your registry)
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com # Or your private registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile # Your Dockerfile path
          push: true
          tags: your-dockerhub-username/your-image-name:latest 
          # Example: your-dockerhub-username/your-image-name:latest
